install:
 - mvn -B clean
script:
 - travis_wait 60 mvn -B -Ptravis -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} install

language: java
jdk:
  - openjdk12
  - openjdk13
env:
  - SERVER_VERSION=18.0.0.Final
  - SERVER_VERSION=18.0.0.Final ELYTRON=true
jobs:
  include:
    - stage: "javadoc"
      script: mvn -B -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk12
      env: SERVER_VERSION=18.0.0.Final
    - stage: "javadoc"
      script: mvn -B -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk13
      env: SERVER_VERSION=18.0.0.Final
addons:
  hosts:
    - localhost.localdomain
cache:
 directories:
  - $HOME/.m2
