install:
 - mvn clean
script:
 - mvn -B -fn install

language: java
jdk:
  - oraclejdk8
env:
  - server.version=10.1.0.CR1
  - server.version=10.0.0.Final
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
    - "sudo unzip -j -o  travis-libs/jce_policy-8.zip *.jar -d $JAVA_HOME/jre/lib/security"
